name: DeathView
author: lukeeey
description: Go into spectator mode when you die. Like Mineplex.
version: ${project.version}
api: [1.0.5]
main: io.github.lukeeey.deathview.DeathView
website: https://github.com/lukeeey/DeathView
permissions:
  deathview.spectator:
    description: Allows a player to make use of the functionalliy of DeathView
    default: true